version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  django:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
         python manage.py migrate &&
         python manage.py collectstatic --noinput &&
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
      - redis
    networks:
      - my_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - my_network

  celery:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A api_task worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis_cache:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_cache:6379/0
      - DB_HOST=postgres  
      - DB_PORT=5432
    depends_on:
      - redis
      - postgres
    networks:
      - my_network

volumes:
  postgres_data: