# Generated by Django 5.1.2 on 2024-11-19 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_project_project_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="assigned_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
