# Generated by Django 5.1.2 on 2024-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_manager", "Project Manager"),
                    ("developer", "Developer"),
                    ("sqa", "Software Quality Assurance"),
                ],
                default="developer",
                max_length=20,
            ),
        ),
    ]
