# Generated by Django 5.1.2 on 2024-11-20 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
