# Generated by Django 5.1.2 on 2024-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_manager", "Project Manager"),
                    ("developer", "Developer"),
                    ("software_quality_assurance", "Software Quality Assurance"),
                ],
                default="developer",
                max_length=50,
            ),
        ),
    ]
