# Generated by Django 5.1.2 on 2024-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
